name:                com
version:             0.1.0.0
github:              "githubuser/com"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/com#readme>

dependencies:
- base >= 4.7 && < 5
- split >= 0.2.3.0
- binary >= 0.8.5
- bytestring >= 0.10.8.0
- aeson
- text
- matrix
- fsnotify
- directory
- filepath

library:
  source-dirs: src

executables:
  monitor:
    main:                Main.hs
    source-dirs:         app/monitor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - com

  tojson:
    main:                Main.hs
    source-dirs:         app/tojson
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - com

tests:
  com-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - com
